// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rttnelgyfzufpssbcrky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dG5lbGd5Znp1ZnBzc2Jjcmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTM0MzYsImV4cCI6MjA2OTc2OTQzNn0.118lmMIrXns2_j8a5-qeaxeUWrwi_Dn7uOAfGhKtkiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});